pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/shreerakshabm99/frontendapp.git', branch: 'dev'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('login-app') {
                    bat 'npm install'
                }
            }
        }

        stage('Build') {
            steps {
                dir('login-app') {
                    bat 'npm run build'
                }
            }
        }

       stage('Testing') {
    steps {
        dir('login-app') {
            bat 'npm install sonar-scanner --save-dev'
'
        }
    }
}

        stage('Test') {
    steps {
        dir('login-app') {
            bat 'npm test -- --coverage --watchAll=false --passWithNoTests'
        }
    }
}


        stage('SonarQube Analysis') {
            steps {
                dir('login-app') {
                    withSonarQubeEnv('SonarQube Server') {
                        bat 'npm run sonar'
                    }
                }
            }
        }

        stage('Archive Build') {
            steps {
                dir('login-app') {
                    archiveArtifacts artifacts: 'build/**', fingerprint: true
                }
            }
        }
    }
}
