pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/shreerakshabm99/frontendapp.git', branch: 'dev'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('login-app') {
                    bat 'npm install'
                }
            }
        }

        stage('Build') {
            steps {
                dir('login-app') {
                    bat 'npm run build'
                }
            }
        }

        stage('Test') {
            steps {
                dir('login-app') {
                    bat 'npm test -- --coverage --watchAll=false'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('login-app') {
                    withSonarQubeEnv('MySonar') {
                        bat 'sonar-scanner'
                    }
                }
            }
        }

        stage('Archive Build') {
            steps {
                dir('login-app') {
                    archiveArtifacts artifacts: 'build/**', fingerprint: true
                }
            }
        }
    }
}
